rm "airfoil_self_noise.dat"
rm "Relation Network (Directed).data"
rm "machine.data"
rm "slump_test.data"
rm "communities.data"
rm "yacht_hydrodynamics.data"
rm "Concrete_Data.xls"
rm "2014 and 2015 CSM dataset.xlsx"
rm "CASP.csv"
rm "dataset_Facebook.csv"
rm "Facebook_metrics.txt"
rm "transcoding_mesurment.tsv"
rm "youtube_videos.tsv"
rm "README.txt"
rm -r "OnlineNewsPopularity"
rm "slice_localization_data.csv"
rm -r "UJIndoorLoc"
rm "news20.scale"
rm "news20.t.scale"